[tool.poetry]
name = "almonds"
version = "0.1.0"
description = ""
authors = ["kentonvp <kentonvanp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.3"
sqlalchemy = "^2.0.31"
pydantic = "^2.7.4"
email-validator = "^2.2.0"
plaid-python = "^23.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.8.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
