MAX_USERNAME_LENGTH = 20
MAX_PASSWORD_HASH_LENGTH = 162
MAX_EMAIL_LENGTH = 320

MAX_CATEGORY_NAME_LENGTH = 50

MAX_TRANSACTION_NAME_LENGTH = 120
MAX_DESCRIPTION_LENGTH = 255

MAX_DOLLAR_DIGITS = 10

MAX_STATUS_LENGTH = 20

MAX_GOAL_NAME_LENGTH = 100
